Repository VitalyPeryatin/1Coin, pull requests merged in 2022-11, with the labels that each got.

#79 Добавил 'редактирование транзакции'
  android/src/main/kotlin/com/finance_tracker/finance_tracker/data/broadcast_receivers/SmsBroadcastReceiver.kt
  android/src/main/kotlin/com/finance_tracker/finance_tracker/data/broadcast_receivers/parsers/SmsMessageParser.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/DataExtensions.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/DialogConfigurations.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/navigation/main/MainNavigationGraph.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/transactions/TransactionItem.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/repositories/TransactionsRepository.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/models/Transaction.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/accounts/AccountsAppBar.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/accounts/AccountsViewModel.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/AddTransactionScreen.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/AddTransactionViewModel.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/views/AddButtonSection.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/views/EnterTransactionStep.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/views/StepsEnterTransactionBar.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/views/enter_transaction_controller/EnterTransactionController.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/AccountsWidget.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/HomeTopBar.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/transactions/TransactionsScreen.kt
  common/src/commonMain/resources/drawable/ic_duplicate.xml
  common/src/commonMain/resources/values/strings.xml
  common/src/commonMain/sqldelight/com/finance_tracker/finance_tracker/TransactionsEntity.sq
Labels: enhancement

#74 FT-70: Modify CI/CD
  .github/workflows/android.yml
  android/build.gradle.kts
  android/detekt.gradle
  android/src/main/kotlin/com/finance_tracker/finance_tracker/MainActivity.kt
  build.gradle.kts
  common/build.gradle.kts
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/core/ui/GridGropdownMenu.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/DragDropState.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/LazyDragColumn.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/GridDropdownMenuContent.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/network/CurrenciesNetworkDataSource.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/di/CoreModule.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_category/AddCategoryScreen.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_category/views/ChooseIconButton.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/AddTransactionViewModel.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/views/enter_transaction_controller/AccountCard.kt
  common/src/desktopMain/kotlin/com/finance_tracker/finance_tracker/core/common/KoinContainer.kt
  common/src/desktopMain/kotlin/com/finance_tracker/finance_tracker/core/ui/GridDropdownMenu.kt
  config/detekt/detekt.yml
  desktop/build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#82 FT-73: Add Ktor logging
  android/src/main/kotlin/com/finance_tracker/finance_tracker/App.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/di/CoreModule.kt
  desktop/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/main.kt
Labels: enhancement

#85 FT-83: Prepare SQLDelight for future migrations
  android/src/main/kotlin/com/finance_tracker/finance_tracker/data/broadcast_receivers/SmsBroadcastReceiver.kt
  common/build.gradle.kts
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/database/DatabaseInitializer.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/database/mappers/AccountsEntityMapper.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/database/mappers/CategoriesEntityMapper.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/database/mappers/DefaultCategoriesEntityMapper.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/repositories/AccountsRepository.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/repositories/CategoriesRepository.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/repositories/CurrenciesRepository.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/repositories/TransactionsRepository.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/di/DatabaseModule.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/CurrencyConverterInteractor.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/AddTransactionViewModel.kt
  common/src/commonMain/sqldelight/com/finance_tracker/finance_tracker/data/AccountColorsEntity.sq
  common/src/commonMain/sqldelight/com/finance_tracker/finance_tracker/data/AccountsEntity.sq
  common/src/commonMain/sqldelight/com/finance_tracker/finance_tracker/data/CategoriesEntity.sq
  common/src/commonMain/sqldelight/com/finance_tracker/finance_tracker/data/CurrencyRatesEntity.sq
  common/src/commonMain/sqldelight/com/finance_tracker/finance_tracker/data/DefaultCategoriesEntity.sq
  common/src/commonMain/sqldelight/com/finance_tracker/finance_tracker/data/SmsMessageEntity.sq
  common/src/commonMain/sqldelight/com/finance_tracker/finance_tracker/data/TransactionsEntity.sq
  common/src/commonMain/sqldelight/com/finance_tracker/finance_tracker/schemas/1.db
  config/detekt/detekt.yml
Labels: enhancement

#86 Добавил возможность подключения pre-commit
  CONTRIBUTING.md
  build.gradle.kts
  hooks/pre-commit
Labels: enhancement

#87 Добавил проверку verifyDatabaseMigration для CI/CD и pre-commit
  .github/workflows/android.yml
  hooks/pre-commit
Labels: enhancement

#88 FT-87: Add 'koalaplot' library for charts
  README.md
  common/build.gradle.kts
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/analytics/AnalyticsScreen.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/analytics/PieChart.kt
  gradle/libs.versions.toml
Labels: enhancement

#89 FT-79: Optimize detekt for Compose
  android/src/main/kotlin/com/finance_tracker/finance_tracker/data/broadcast_receivers/parsers/models/SmsTemplate.kt
  build.gradle.kts
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/core/ui/CalendarDialog.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/core/ui/CoinDropdownMenu.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/core/ui/CoinGridDropdownMenu.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/core/ui/GridGropdownMenu.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/CommonBackHandler.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/DragDropState.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/StringHex.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/theme/AppColors.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/theme/CoinShape.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/theme/CoinTheme.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/theme/CoinTypography.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/AppBarIcon.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/CategoryCard.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/CoinGridDropdownMenu.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/ExpenseIncomeTabs.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/GridDropdownMenuContent.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/ItemWrapper.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/PrimaryButton.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/TextFields.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/collapsing_toolbar/CollapsingToolbar.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/collapsing_toolbar/CollapsingToolbarScaffold.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/transactions/CommonTransactionList.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/TransactionsInteractor.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_category/AddCategoryScreen.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/AddTransactionViewModel.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/views/AddButtonSection.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/views/CategoriesAppBar.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/views/EnterTransactionStep.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/views/StepsEnterTransactionBar.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/views/enter_transaction_controller/AmountKeyboard.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/detail_account/DetailAccountScreen.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/detail_account/views/AccountNameText.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/AccountsWidget.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/views/SettingsSheetCategorySettingsItem.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/tabs_navigation/TabsNavigationScreen.kt
  common/src/desktopMain/kotlin/com/finance_tracker/finance_tracker/core/ui/CalendarDialog.kt
  common/src/desktopMain/kotlin/com/finance_tracker/finance_tracker/core/ui/CoinDropdownMenu.kt
  common/src/desktopMain/kotlin/com/finance_tracker/finance_tracker/core/ui/CoinGridDropdownMenu.kt
  common/src/desktopMain/kotlin/com/finance_tracker/finance_tracker/core/ui/GridDropdownMenu.kt
  config/detekt/detekt.yml
  gradle.properties
Labels: enhancement

#90 FT-80: Modified add/edit transaction steps
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_transaction/AddTransactionScreen.kt
Labels: enhancement

#91 Hotfix: add dialog when account deletes
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_account/AddAccountScreen.kt
  common/src/commonMain/resources/values/strings.xml
Labels: bug

#93 FT-89: Implement transition to telegram chat in settings
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/views/SettingsSheetTelegramChatItem.kt
  common/src/commonMain/resources/drawable/telegram.xml
  common/src/commonMain/resources/values/strings.xml
Labels: enhancement

#92 FT-78: Implement transactions delete animation
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/transactions/CommonTransactionList.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/TransactionsInteractor.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/models/TransactionListModel.kt
Labels: bug, enhancement

#94 Add convention plugins
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/android-setup.gradle.kts
  buildSrc/src/main/kotlin/multiplatform-compose-setup.gradle.kts
  common/build.gradle.kts
  common/src/androidMain/AndroidManifest.xml
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement

#95 FT-93: Change minSdk 24 -> 26
  android/build.gradle.kts
  buildSrc/src/main/kotlin/android-setup.gradle.kts
Labels: enhancement
